apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-yonis-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dooz34/EKS-PROJECT-V1.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true